"""avatar_hash added to User models.py

Revision ID: 314446e656a6
Revises: 84a83d3698bc
Create Date: 2019-07-09 18:10:42.830557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314446e656a6'
down_revision = '84a83d3698bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
