"""users table added birthday_date

Revision ID: 6bfa8a9c078b
Revises: d5c4b8fa3f7d
Create Date: 2020-02-05 22:17:02.826318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfa8a9c078b'
down_revision = 'd5c4b8fa3f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday_date')
    # ### end Alembic commands ###
